### ISSUE TITLE
Copyright missing

### ISSUE THREAD

**Issue by seancorfield** [prestancedesign/usermanager-reitit-integrant-example#1]
Since much of the code is copied from https://github.com/seancorfield/usermanager-example you should reinstate the copyright notices from that code, as well as the license under which it was released.

It would also be useful to beginners to add a README, linking back to the original repo and explaining the differences. Feel free to copy chunks of my readme to get started.

**Comment by prestancedesign** [comment]
Thanks for the advice, that was my intention before begins to sharing the repo.

As English it's not my first language, it's more easy/fun to write in Clojure than a Readme file. :)
> Feel free to copy chunks of my readme to get started.

It will help me a lot, thank you.

**Comment by prestancedesign** [comment]
It's done.

I am open to any comments or suggestions.
Thanks again.

**Comment by seancorfield** [comment]
Thanks. In the README, looks like `[next.jdbc](https://cljdoc.org/d/seancorfield/next.jdbc)` should be `[[https://cljdoc.org/d/seancorfield/next.jdbc][next.jdbc]]`.

**Comment by prestancedesign** [comment]
Thanks for the feedback, it's fixed.
