### ISSUE TITLE
Production set up

### ISSUE THREAD

**Issue by NoahTheDuke** [prestancedesign/usermanager-reitit-integrant-example#2]
Thanks for setting this up! It's really helpful to see all these pieces working together.

How does running this as an uberjar work? What steps or set up do I need to do to make it production ready?

**Comment by prestancedesign** [comment]
Thanks for your feedback and these kinds words!
Glad to know that this project is helpful.

I don't know why but I did not receive any notifications, I just seen your issue.
Since then have you found a solution?

**Comment by NoahTheDuke** [comment]
I have been caught up with other stuff, so haven't had time to move my app over to reitit, but it's still something I want to do in the future. So, take your time!

**Comment by prestancedesign** [comment]
FYI, just commited the setup to build an Uberjar. Check this new section on the readme: https://github.com/prestancedesign/usermanager-reitit-example#build-an-uberjar

This should answer this issue, so I close it.
Let me know if you have any questions about it.

**Comment by NoahTheDuke** [comment]
Thank you so much for the follow up! I'll read through it and see how our approaches compare.
